### ISSUE TITLE
Execute me, anything update of the whole repository?  Lots of missing files in yours code such as `prompt_spec_path` which is one of the most important instruction prompts.

### ISSUE THREAD

**Issue by kanseaveg** [TIGER-AI-Lab/StructLM#5]
![image](https://github.com/TIGER-AI-Lab/StructLM/assets/80022154/c667fb87-071a-4834-8b34-d79818cebdea)

**Comment by azhx** [comment]
Hi, thanks for your interest in this repo! I just reorganized the whole thing. I will write up a readme tomorrow. Sorry for the delay and thanks for your patience. The prompts are already uploaded under `prompts/` but I will provide the processed test dataset so that you don't need to construct it yourself.

**Comment by kanseaveg** [comment]
Thank you for your patient answers, and thank you for your contributions to the community.
