### ISSUE TITLE
Missing file when trying to run evaluation script

### ISSUE THREAD

**Issue by iwinterknight** [TIGER-AI-Lab/StructLM#7]
Thanks for sharing your code!
I downloaded the datasets and the 7B model ckpt from the download bash script you uploaded. I'm unable to get the `run_test_eval.sh` to run.

I get the error : [Errno 2] No such file or directory: './output/StructLM-13B/predictions_predict.json'

**Comment by kanseaveg** [comment]
I have encountered this problem before. Later, I manually modified the code and completed the missing packages in requirements.txt.

Firstly, you should add the following sentence before that one.
```os.makedirs(output_path, exist_ok=True)```

![image](https://github.com/TIGER-AI-Lab/StructLM/assets/80022154/a3c7bee5-882a-4464-a0b5-344f9edcd30d)

Next, you should add these two packages to the requirements.txt file and execute pip install for installation.
```datasets```
```megablocks```
```scipy```
![image](https://github.com/TIGER-AI-Lab/StructLM/assets/80022154/9c57e20c-65e8-49e6-b707-2d45e8e7e2eb)




Finally, by using the execute script command: **`./run_test_eval.sh StructLM-7B`** , it should be possible to evaluate.
Because my contribution is too small, I won't submit a Pull request.

Although I'm grateful for their contributions, it seems that they haven't provided reproducible training scripts and training tutorials. This might be a regret, perhaps. @iwinterknight 

In terms of time, the evaluation of 7B is very fast.
![image](https://github.com/TIGER-AI-Lab/StructLM/assets/80022154/8f577c1f-4737-4cd7-aa77-beb38ef1898d)

**Comment by azhx** [comment]
Hi, thanks for the suggestions, I updated the requirements.txt. I'm continuing to test and improve this repo.
